### ISSUE TITLE
Ability to disable console tips

### ISSUE THREAD

**Issue by kchung** [privatenumber/vue-dom-hints#5]
Hello, big fan of this plugin. But is there a way to configure disabling the "tips" that are logged out into the console? I currently have a lot of output on page load, but would like to have control of reducing this.

This is a fresh page load:

![90078183-ead2d400-dcb8-11ea-9187-33f986d5f5ac](https://user-images.githubusercontent.com/879656/90078324-5c128700-dcb9-11ea-8bfb-094bc6ba4550.png)

(Yeah I agree this "Orbit" library is really noisy)

**Comment by privatenumber** [comment]
Thank you @kchung 👌
